---
name: XOA Arm64 Builder

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docker-compose.yml'
      - '.github/**'
    branches:
      - "main"

jobs:
  build:
    runs-on: debian-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3


  